development:
  adapter: postgresql
  encoding: unicode
  database: vielfalt-teilen_development

test:
  adapter: postgresql
  encoding: unicode
  database: vielfalt-teilen_test

production:
  adapter: postgresql
  encoding: unicode
  database: vielfalt-teilen_production
